name: Code quality check
on:
  push:
  pull_request:
jobs:
  code-check:
    name: Code quality check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
      - name: Check code format
        run: npm run format:check
      - name: Check lint error
        run: npm run
